name: MarkdownConverter
kind: pipeline
type: docker

steps:
  - name: install
    image: node
    commands:
      - npm install --unsafe-perm
  - name: build
    image: node
    commands:
      - npm run build-debug
  - name: lint
    image: node
    commands:
      - npm run lint
  - name: test
    image: manuth/vscode-test-runner
    commands:
      - xvfb-run npm run test -- --disable-gpu --headless
  - name: publish extension
    image: node:lts
    environment:
      ACCESS_TOKEN:
        from_secret: azure_token
    commands:
    - npx vsce publish --no-yarn --pat $ACCESS_TOKEN
    when:
      event:
      - tag
      ref:
        - refs/tags/v[0-9]*.[0-9]*.[0-9]*
  - name: prepare release
    image: node:lts
    commands:
      - npx vsce package --no-yarn
      - npm install @stdlib/utils-escape-regexp-string --no-save
      - node -e "console.log(require('@stdlib/utils-escape-regexp-string')('${DRONE_TAG}'))" > .tagName.txt
    when:
      event:
        - tag
  - name: prepare release notes
    image: alpine
    commands:
      - export TagName=$$(cat .tagName.txt)
      - export TagHeading="/## \(.* \($${TagName}\|\[$${TagName}\]\)\)\$/"
      - export HeadingPattern='/## \(.* \(v[0-9.]*\|\[.*\]\)\)/'
      - cp -f CHANGELOG.md .releaseNotes.md
      - sed -i "1,$${TagHeading}{ $${TagHeading}P ; d } ; $${HeadingPattern},\$d" .releaseNotes.md
      - cp -f .releaseNotes.md .releaseTitle.md
      - sed -i "2,\$d ; s$${HeadingPattern}\\\\1/" .releaseTitle.md
    when:
      event:
        - tag
  - name: publish release
    image: plugins/github-release
    commands: []
    settings:
      api_key:
        from_secret: github_publish_token
      files:
        - "*.vsix"
      title: .releaseTitle.md
      note: .releaseNotes.md
    when:
      event:
        - tag

trigger:
  ref:
    - refs/heads/**
    - refs/pull/**
    - refs/tags/**
  event:
    - push
    - pull_request
    - tag
