// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/428195bee21d60868efcb2dbcb90b7ab01b88aa4/temp/index.d.ts
declare module 'temp' {
// Type definitions for temp 0.8.3
// Project: https://www.npmjs.com/package/temp, https://github.com/bruce/node-temp
// Definitions by: Daniel Rosenwasser <https://github.com/DanielRosenwasser>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="node" />

import * as temp from 'temp';
import * as fs from 'fs';

export interface OpenFile {
  path: string;
  fd: number;
}

export interface Stats {
  files: number;
  dirs: number;
}

export interface AffixOptions {
  prefix?: string;
  suffix?: string;
  dir?: string;
}

export var dir: string;

export function track(value?: boolean): typeof temp;

export function mkdir(affixes?: string, callback?: (err: any, dirPath: string) => void): void;
export function mkdir(affixes?: AffixOptions, callback?: (err: any, dirPath: string) => void): void;

export function mkdirSync(affixes?: string): string;
export function mkdirSync(affixes?: AffixOptions): string;

export function open(affixes?: string, callback?: (err: any, result: OpenFile) => void): void;
export function open(affixes?: AffixOptions, callback?: (err: any, result: OpenFile) => void): void;

export function openSync(affixes?: string): OpenFile;
export function openSync(affixes?: AffixOptions): OpenFile;

export function path(affixes?: string, defaultPrefix?: string): string;
export function path(affixes?: AffixOptions, defaultPrefix?: string): string;

export function cleanup(callback?: (result: boolean | Stats) => void): void;

export function cleanupSync(): boolean | Stats;

export function createWriteStream(affixes?: string): fs.WriteStream;
export function createWriteStream(affixes?: AffixOptions): fs.WriteStream;
}
