import { Extension } from "../extension";
import { Command } from "./Command";
import { Converter } from "./Converter";

/**
 * Provides a command for converting a markdown-document.
 */
export class ConvertCommand extends Command
{
    /**
     * Initializes a new instance of the `ConvertCommand` class.
     * 
     * @param extension
     * The extension the command belongs to.
     */
    public constructor(extension: Extension)
    {
        super(extension);
    }

    /**
     * Loads a converter according to the settings.
     * 
     * @returns
     * A converter generated by the settings.
     */
    protected LoadConverter(): Converter
    {
        return null;
    }

    public Execute()
    {
        throw new Error("Method not implemented.");
    }
}